# Generated by Django 4.0.6 on 2022-08-17 12:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('username', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('firstName', models.CharField(default='FirstName', max_length=20)),
                ('lastName', models.CharField(default='LastName', max_length=20)),
                ('userStatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equlpment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('material', models.CharField(max_length=20)),
                ('frequencyType', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('buildingName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Physical_Sensor_manager',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('serialNumber', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('cycle', models.CharField(max_length=20)),
                ('onlineTime', models.CharField(max_length=20)),
                ('lastUploadDataTime', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UUID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('cycle', models.CharField(max_length=10)),
                ('installLocation', models.CharField(max_length=10)),
                ('equipmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBInterface.equlpment')),
                ('physicalSensorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBInterface.physical_sensor_manager')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('power', models.IntegerField()),
                ('voltage', models.FloatField()),
                ('electric', models.FloatField()),
                ('photo', models.TextField()),
                ('fieldId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBInterface.field')),
            ],
        ),
        migrations.AddField(
            model_name='equlpment',
            name='machineId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBInterface.machine'),
        ),
    ]
