# Generated by Django 4.0.6 on 2022-08-18 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBInterface', '0002_account_permission_equlpment_fladecount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='floor',
            field=models.CharField(default='floor', max_length=10),
            preserve_default=False,
        ),
    ]
