# Generated by Django 4.0.6 on 2022-08-18 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBInterface', '0003_field_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='physical_sensor_manager',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='equlpment',
            name='brand',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='equlpment',
            name='frequencyType',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='equlpment',
            name='material',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='equlpment',
            name='model',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='equlpment',
            name='photo',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='field',
            name='buildingName',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='field',
            name='floor',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='machine',
            name='brand',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='machine',
            name='model',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='machine',
            name='photo',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='physical_sensor_manager',
            name='brand',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='physical_sensor_manager',
            name='cycle',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='physical_sensor_manager',
            name='lastUploadDataTime',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='physical_sensor_manager',
            name='model',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='physical_sensor_manager',
            name='onlineTime',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='physical_sensor_manager',
            name='serialNumber',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='cycle',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='installLocation',
            field=models.CharField(default='', max_length=10),
        ),
    ]
